apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: salesforce-ext
  namespace: default
spec:
  host: salesforce.egress.mesh
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: salesforce-timeouts
  namespace: default
spec:
  hosts: ["salesforce.egress.mesh"]
  http:
    - timeout: 3s
      retries:
        attempts: 2
        perTryTimeout: 1.5s
        retryOn: "5xx,connect-failure,refused-stream"
