/// <reference types="next" />
/// <reference types="next/types/global" />
/// <reference types="next/image-types/global" />
/// <reference types="react" />

// NOTE: This file is auto-generated by Next.js and should not be edited manually.
